### ISSUE TITLE
Is there favoritesmenu.swf changes available?

### ISSUE THREAD

**Issue by hellozyemlya** [Vermunds/ExtendedHotkeySystem-SE#1]
Is there changes made to favoritesmenu.swf available? Maybe they can be documented somehow?

**Comment by Vermunds** [comment]
Well, the bad news is that I never documented it and it's been a couple years since I did it so my memory is patchy at best (I don't really have to change this part of the mod)
The good news is that I did explain it to someone before, so below is this copy-pasted, but if you need more info I will also have to look into myself.

The modifications are based on the source of SkyUI [here](https://github.com/schlangster/skyui). This is for oldrim, but in the case of favorites menu it doesn't make much difference.

What was changed:

- In the file, `FavoritesListEntry.as` you have to remove all references to `hotkeyIcon`. This is because the .dll accesses the icons directly, and leaving the actionscript can cause problems when displaying them. The relevant section starting from line 55 should look like this:

```actionscript
if (selectIndicator != undefined)
	selectIndicator._visible = isSelected;

if (a_entryObject.text == undefined) {
	textField.SetText(" ");
} else {
	textField.SetText(a_entryObject.text);
	
	var maxTextLength: Number = 32;
	if (textField.text.length > maxTextLength) {
		textField.SetText(textField.text.substr(0, maxTextLength - 3) + "...");
	}
}
```

- Now comes the part where we add in the hotkey icons. I was using the `buttonArt.fla` file for this, from the resources folder. The process is relatively easy: Rename the movie clip from `ButtonArt` to `HotkeyIcon`, remove the AS linkage, and simply copy paste it into `FavoritesMenu.fla`, overwriting the existing hotkey icon. You will have to adjust the position afterwards, and that's it. It should now work with my mod.

You can also create your own hotkey icons from scratch if you wish. In that case, just make sure that the frame number that is displaying the button, corresponds to the button's Directinput scan code (if you do, I recommend putting the anchor point to the right side, so that larger symbols don't clip with the scroll bar, like they do now. Numpad enter is probably the worst.)

**Comment by hellozyemlya** [comment]
Many thanks for reply.
